[package]
name = "imgui_baseplug_baseview_test"
version = "0.1.0"
authors = ["DGriffin <github@dgdigital.net>"]
edition = "2018"
license = "MIT"

[lib]
name = "imgui_baseplug_baseview_test"
crate-type = ["cdylib"]

[dependencies]
baseplug = { git = "https://github.com/wrl/baseplug.git", branch="trunk" }
serde = { version = "1.0", features = ["derive"] }
baseview = {git = "https://github.com/RustAudio/baseview", branch = "master"}
dirs = "3"
log = "0.4"
log-panics = "2"
raw-window-handle = "0.3"
simplelog = "0.8"
vst = "0.2"
rtrb = "0.1.1"
imgui-baseview = {git = "https://github.com/BillyDM/imgui-baseview", branch = "main"}
imgui = "0.7"
